import type { Dataset, Fixture, Performance } from "../src/data";

const uuid = (value: number) =>
	`00000000-0000-4000-8000-${String(value).padStart(12, "0")}`;
const notts = uuid(1),
	opponent = uuid(2),
	forward = uuid(3),
	goalkeeper = uuid(4),
	awayPlayer = uuid(5);
const season = uuid(6),
	league = uuid(7),
	cup = uuid(8),
	preseason = uuid(9);
const leagueEdition = uuid(10),
	cupEdition = uuid(11),
	preseasonEdition = uuid(12);

function match(value: number, overrides: Partial<Fixture>): Fixture {
	return {
		id: uuid(value),
		competition_season_id: leagueEdition,
		played_on: "2018-08-01",
		home_club_id: notts,
		away_club_id: opponent,
		home_goals: 2,
		away_goals: 0,
		home_penalties: null,
		away_penalties: null,
		venue: "Test Ground",
		duration_minutes: 90,
		extra_time: false,
		round: null,
		...overrides,
	};
}

function performance(
	value: number,
	overrides: Partial<Performance>,
): Performance {
	return {
		id: uuid(value),
		match_id: uuid(20),
		player_id: forward,
		club_id: notts,
		overall: 62,
		rating: 8,
		displayed_position: "ST",
		goals: 2,
		assists: 0,
		minutes_played: null,
		goals_conceded: null,
		goals_conceded_displayed: null,
		shots_on_target: 3,
		...overrides,
	};
}

export const fixture: Dataset = {
	schema_version: 3,
	generated_at: "2026-01-01T00:00:00Z",
	clubs: [
		{ id: notts, name: "Notts County" },
		{ id: opponent, name: "Portsmouth" },
	],
	players: [
		{ id: forward, name: "Test Forward", nationality: "England" },
		{ id: goalkeeper, name: "Test Goalkeeper", nationality: "England" },
		{ id: awayPlayer, name: "Test Opponent", nationality: null },
	],
	seasons: [{ id: season, label: "2018/19" }],
	competitions: [
		{
			id: league,
			name: "EFL League Two",
			kind: "league",
			is_preseason: false,
		},
		{
			id: cup,
			name: "Checkatrade Trophy",
			kind: "cup",
			is_preseason: false,
		},
		{
			id: preseason,
			name: "Invitational Cup",
			kind: "cup",
			is_preseason: true,
		},
	],
	competition_seasons: [
		{ id: leagueEdition, competition_id: league, season_id: season },
		{ id: cupEdition, competition_id: cup, season_id: season },
		{ id: preseasonEdition, competition_id: preseason, season_id: season },
	],
	matches: [
		match(20, {}),
		match(21, {
			played_on: "2018-08-08",
			home_club_id: opponent,
			away_club_id: notts,
			home_goals: 1,
			away_goals: 1,
		}),
		match(22, {
			played_on: "2019-02-14",
			competition_season_id: cupEdition,
			home_goals: 0,
			home_penalties: 4,
			away_penalties: 3,
		}),
		match(23, {
			played_on: "2018-07-04",
			competition_season_id: preseasonEdition,
			home_goals: 1,
			away_goals: 1,
		}),
	],
	team_matches: [],
	player_matches: [
		performance(30, {}),
		performance(31, {
			player_id: goalkeeper,
			displayed_position: "GK",
			goals: null,
			rating: 7.2,
			goals_conceded: 0,
			goals_conceded_displayed: 0,
		}),
		performance(32, { match_id: uuid(21), goals: 0, assists: 1 }),
		performance(33, { match_id: uuid(22), goals: 0 }),
		performance(34, {
			match_id: uuid(21),
			player_id: awayPlayer,
			club_id: opponent,
			goals: 1,
		}),
	],
	player_snapshots: [
		{
			id: uuid(40),
			player_id: forward,
			season_id: season,
			club_id: notts,
			match_id: null,
			overall: 62,
			displayed_position: "ST",
			snapshot_kind: "season_start",
			observed_on: null,
			date_precision: "season",
		},
		{
			id: uuid(41),
			player_id: forward,
			season_id: season,
			club_id: notts,
			match_id: null,
			overall: 70,
			displayed_position: "ST",
			snapshot_kind: "season_end",
			observed_on: null,
			date_precision: "season",
		},
	],
	player_competition_snapshots: [
		{
			id: uuid(50),
			player_id: forward,
			club_id: notts,
			season_id: season,
			competition_season_id: null,
			scope: "all_competitions",
			snapshot_kind: "season_end",
			appearances: 3,
			goals: 2,
			assists: 1,
			clean_sheets: 0,
			yellow_cards: 0,
			red_cards: 0,
			average_rating: 8,
		},
		{
			id: uuid(51),
			player_id: forward,
			club_id: notts,
			season_id: season,
			competition_season_id: leagueEdition,
			scope: "competition",
			snapshot_kind: "season_end",
			appearances: 2,
			goals: 2,
			assists: 1,
			average_rating: 8,
		},
		{
			id: uuid(52),
			player_id: forward,
			club_id: notts,
			season_id: season,
			competition_season_id: cupEdition,
			scope: "competition",
			snapshot_kind: "season_end",
			appearances: 1,
			goals: 0,
			assists: 0,
			average_rating: 8,
		},
	],
	player_transfers: [
		{
			id: uuid(60),
			player_id: forward,
			from_club_id: opponent,
			to_club_id: notts,
			transfer_type: "loan",
			effective_on: null,
			contract_months: 24,
			loan_months: 12,
			fee_minor: null,
		},
	],
	competition_events: [
		{
			id: uuid(61),
			competition_season_id: leagueEdition,
			event_type: "promotion",
			announced_on: "2019-05-01",
			period: null,
			player_id: null,
			description: "Promotion confirmed",
		},
	],
	coverage: {
		records: {
			matches: 4,
			players: 3,
			player_matches: 5,
			player_snapshots: 2,
		},
	},
	match_coverage: {
		summary: {
			matches: 4,
			preseason_matches: 1,
			player_records: 4,
			minimum_player_records_per_match: 0,
			maximum_player_records_per_match: 2,
			matches_with_two_complete_team_rows: 0,
			matches_with_complete_player_core_fields: 0,
			warning_count: 1,
		},
		warnings: [
			{
				code: "player_goal_difference",
				match_id: uuid(21),
				played_on: "2018-08-08",
				home_club: "Portsmouth",
				away_club: "Notts County",
				team_goals: 1,
				credited_player_goals: 2,
				difference: -1,
				title: "Player goals exceed team score",
				detail: "Credited player goals exceed the team score.",
			},
		],
		player_field_availability: {},
	},
	season_reconciliation: {
		summary: {
			rows: 1,
			matched_rows: 0,
			mismatched_rows: 0,
			partial_rows: 1,
		},
		comparisons: [
			{
				snapshot_id: uuid(70),
				player_id: goalkeeper,
				player: "Test Goalkeeper",
				season: "2018/19",
				competition: null,
				scope: "all_competitions",
				result: "partial",
				metrics: {
					appearances: {
						observed: 1,
						derived: 1,
						result: "match",
						difference: 0,
						missing_match_values: 0,
					},
					goals: {
						observed: null,
						derived: null,
						result: "unavailable",
						difference: null,
						missing_match_values: 1,
					},
					average_rating: {
						observed: 7.2,
						derived: 7.2,
						raw_match_average: 7.234,
						result: "match",
						difference: 0,
						missing_match_values: 0,
					},
				},
			},
		],
		limitations: [],
	},
};
